services:
  - type: web
    name: binance-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "8021146799:AAFYJR3G72OS3Xk_kmA79aG1XZdiudcLLDs"
      - key: CHAT_ID
        value: "6419058496"
